### ISSUE TITLE
I need to create POST requests with different body each one

### ISSUE THREAD

**Issue by destructorvad** [abstracta/jmeter-dotnet-dsl-sample#1]
Hello
I have a big model (generating using Bogus lib) - I want to run Post Requests to create a lot of entities. Are there any ways to implement this?
I'v found you advised to use PreProcessor here - https://github.com/abstracta/jmeter-java-dsl/issues/7 - but there is no PreProcessor class in dotnet dsl.
Tnanks!

**Comment by rabelenda** [comment]
I will close this since is related to the DSL and not particularly to the sample project and you have already created this issue: https://github.com/abstracta/jmeter-dotnet-dsl/issues/3
